# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: MAGICC Lab
    url: https://magicc.byu.edu/
    weight: 11
  - name: Research Team
    url: research_team/
    weight: 12
  - name: Papers
    url: https://scholar.google.com/citations?user=JUKswVIAAAAJ&hl=en&oi=ao
    weight: 13
  # - name: Talks
  #   url: /#talks
  #   weight: 14
  # - name: News
  #   url: /#news
  #   weight: 15
  - name: Projects
    url: projects/
    weight: 30
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
  # - name: Experience
  #   url: experience/
  #   weight: 20